/* 
stimOptions (28,6) come from the generate-sequences.py script 
there are 7 final states that have 2 probe states each and there are 2 trial types  
7 * 2 * 2 = 28 trials per participant 
out of the 6 combinations in each list, we only select one at random 
*/

const max = 5;
const min = 0;
const stimOptions = [
    [
        ["jealousy", "anger"],
        ["jealousy", "cheerfulness", "anger"],
        ["jealousy", "enthusiasm", "cheerfulness", "anger"],
        ["jealousy", "excitement", "enthusiasm", "cheerfulness", "anger"],
        [
            "jealousy",
            "pleasure",
            "excitement",
            "enthusiasm",
            "cheerfulness",
            "anger",
        ],
        [
            "jealousy",
            "playfulness",
            "pleasure",
            "excitement",
            "enthusiasm",
            "cheerfulness",
            "anger",
        ],
    ],
    [
        ["jealousy", "anger"],
        ["jealousy", "outrage", "anger"],
        ["jealousy", "panic", "outrage", "anger"],
        ["jealousy", "hate", "panic", "outrage", "anger"],
        ["jealousy", "terror", "hate", "panic", "outrage", "anger"],
        ["jealousy", "envy", "terror", "hate", "panic", "outrage", "anger"],
    ],
    [
        ["patience", "anger"],
        ["patience", "cheerfulness", "anger"],
        ["patience", "enthusiasm", "cheerfulness", "anger"],
        ["patience", "excitement", "enthusiasm", "cheerfulness", "anger"],
        [
            "patience",
            "pleasure",
            "excitement",
            "enthusiasm",
            "cheerfulness",
            "anger",
        ],
        [
            "patience",
            "playfulness",
            "pleasure",
            "excitement",
            "enthusiasm",
            "cheerfulness",
            "anger",
        ],
    ],
    [
        ["patience", "anger"],
        ["patience", "transcendence", "anger"],
        ["patience", "imagination", "transcendence", "anger"],
        ["patience", "pensiveness", "imagination", "transcendence", "anger"],
        [
            "patience",
            "serenity",
            "pensiveness",
            "imagination",
            "transcendence",
            "anger",
        ],
        [
            "patience",
            "relief",
            "serenity",
            "pensiveness",
            "imagination",
            "transcendence",
            "anger",
        ],
    ],
    [
        ["nervousness", "anxiety"],
        ["nervousness", "awe", "anxiety"],
        ["nervousness", "indifference", "awe", "anxiety"],
        ["nervousness", "elation", "indifference", "awe", "anxiety"],
        ["nervousness", "apathy", "elation", "indifference", "awe", "anxiety"],
        [
            "nervousness",
            "wakefulness",
            "apathy",
            "elation",
            "indifference",
            "awe",
            "anxiety",
        ],
    ],
    [
        ["nervousness", "anxiety"],
        ["nervousness", "agitation", "anxiety"],
        ["nervousness", "annoyance", "agitation", "anxiety"],
        ["nervousness", "resentment", "annoyance", "agitation", "anxiety"],
        [
            "nervousness",
            "shock",
            "resentment",
            "annoyance",
            "agitation",
            "anxiety",
        ],
        [
            "nervousness",
            "frustration",
            "shock",
            "resentment",
            "annoyance",
            "agitation",
            "anxiety",
        ],
    ],
    [
        ["patience", "anxiety"],
        ["patience", "awe", "anxiety"],
        ["patience", "indifference", "awe", "anxiety"],
        ["patience", "elation", "indifference", "awe", "anxiety"],
        ["patience", "apathy", "elation", "indifference", "awe", "anxiety"],
        [
            "patience",
            "wakefulness",
            "apathy",
            "elation",
            "indifference",
            "awe",
            "anxiety",
        ],
    ],
    [
        ["patience", "anxiety"],
        ["patience", "serenity", "anxiety"],
        ["patience", "relief", "serenity", "anxiety"],
        ["patience", "contentment", "relief", "serenity", "anxiety"],
        [
            "patience",
            "imagination",
            "contentment",
            "relief",
            "serenity",
            "anxiety",
        ],
        [
            "patience",
            "peacefulness",
            "imagination",
            "contentment",
            "relief",
            "serenity",
            "anxiety",
        ],
    ],
    [
        ["relaxation", "calmness"],
        ["relaxation", "imagination", "calmness"],
        ["relaxation", "appreciation", "imagination", "calmness"],
        [
            "relaxation",
            "contemplation",
            "appreciation",
            "imagination",
            "calmness",
        ],
        [
            "relaxation",
            "affection",
            "contemplation",
            "appreciation",
            "imagination",
            "calmness",
        ],
        [
            "relaxation",
            "friendliness",
            "affection",
            "contemplation",
            "appreciation",
            "imagination",
            "calmness",
        ],
    ],
    [
        ["relaxation", "calmness"],
        ["relaxation", "peacefulness", "calmness"],
        ["relaxation", "relief", "peacefulness", "calmness"],
        ["relaxation", "contentment", "relief", "peacefulness", "calmness"],
        [
            "relaxation",
            "dreaminess",
            "contentment",
            "relief",
            "peacefulness",
            "calmness",
        ],
        [
            "relaxation",
            "serenity",
            "dreaminess",
            "contentment",
            "relief",
            "peacefulness",
            "calmness",
        ],
    ],
    [
        ["suspicion", "calmness"],
        ["suspicion", "imagination", "calmness"],
        ["suspicion", "appreciation", "imagination", "calmness"],
        [
            "suspicion",
            "contemplation",
            "appreciation",
            "imagination",
            "calmness",
        ],
        [
            "suspicion",
            "affection",
            "contemplation",
            "appreciation",
            "imagination",
            "calmness",
        ],
        [
            "suspicion",
            "friendliness",
            "affection",
            "contemplation",
            "appreciation",
            "imagination",
            "calmness",
        ],
    ],
    [
        ["suspicion", "calmness"],
        ["suspicion", "frenzy", "calmness"],
        ["suspicion", "distrust", "frenzy", "calmness"],
        ["suspicion", "stress", "distrust", "frenzy", "calmness"],
        ["suspicion", "alarm", "stress", "distrust", "frenzy", "calmness"],
        [
            "suspicion",
            "bias",
            "alarm",
            "stress",
            "distrust",
            "frenzy",
            "calmness",
        ],
    ],
    [
        ["delight", "happiness"],
        ["delight", "intrigue", "happiness"],
        ["delight", "interconnectedness", "intrigue", "happiness"],
        ["delight", "curiosity", "interconnectedness", "intrigue", "happiness"],
        [
            "delight",
            "earnestness",
            "curiosity",
            "interconnectedness",
            "intrigue",
            "happiness",
        ],
        [
            "delight",
            "interest",
            "earnestness",
            "curiosity",
            "interconnectedness",
            "intrigue",
            "happiness",
        ],
    ],
    [
        ["delight", "happiness"],
        ["delight", "cheerfulness", "happiness"],
        ["delight", "elation", "cheerfulness", "happiness"],
        ["delight", "enjoyment", "elation", "cheerfulness", "happiness"],
        [
            "delight",
            "amusement",
            "enjoyment",
            "elation",
            "cheerfulness",
            "happiness",
        ],
        [
            "delight",
            "pleasure",
            "amusement",
            "enjoyment",
            "elation",
            "cheerfulness",
            "happiness",
        ],
    ],
    [
        ["indecisiveness", "happiness"],
        ["indecisiveness", "intrigue", "happiness"],
        ["indecisiveness", "interconnectedness", "intrigue", "happiness"],
        [
            "indecisiveness",
            "curiosity",
            "interconnectedness",
            "intrigue",
            "happiness",
        ],
        [
            "indecisiveness",
            "earnestness",
            "curiosity",
            "interconnectedness",
            "intrigue",
            "happiness",
        ],
        [
            "indecisiveness",
            "interest",
            "earnestness",
            "curiosity",
            "interconnectedness",
            "intrigue",
            "happiness",
        ],
    ],
    [
        ["indecisiveness", "happiness"],
        ["indecisiveness", "disarray", "happiness"],
        ["indecisiveness", "preoccupation", "disarray", "happiness"],
        [
            "indecisiveness",
            "skepticism",
            "preoccupation",
            "disarray",
            "happiness",
        ],
        [
            "indecisiveness",
            "hunger",
            "skepticism",
            "preoccupation",
            "disarray",
            "happiness",
        ],
        [
            "indecisiveness",
            "uncertainty",
            "hunger",
            "skepticism",
            "preoccupation",
            "disarray",
            "happiness",
        ],
    ],
    [
        ["sorrow", "sadness"],
        ["sorrow", "bewilderment", "sadness"],
        ["sorrow", "ambivalence", "bewilderment", "sadness"],
        ["sorrow", "exasperation", "ambivalence", "bewilderment", "sadness"],
        [
            "sorrow",
            "disbelief",
            "exasperation",
            "ambivalence",
            "bewilderment",
            "sadness",
        ],
        [
            "sorrow",
            "transcendence",
            "disbelief",
            "exasperation",
            "ambivalence",
            "bewilderment",
            "sadness",
        ],
    ],
    [
        ["sorrow", "sadness"],
        ["sorrow", "loneliness", "sadness"],
        ["sorrow", "gloominess", "loneliness", "sadness"],
        ["sorrow", "misery", "gloominess", "loneliness", "sadness"],
        [
            "sorrow",
            "melancholy",
            "misery",
            "gloominess",
            "loneliness",
            "sadness",
        ],
        [
            "sorrow",
            "unhappiness",
            "melancholy",
            "misery",
            "gloominess",
            "loneliness",
            "sadness",
        ],
    ],
    [
        ["anticipation", "sadness"],
        ["anticipation", "bewilderment", "sadness"],
        ["anticipation", "ambivalence", "bewilderment", "sadness"],
        [
            "anticipation",
            "exasperation",
            "ambivalence",
            "bewilderment",
            "sadness",
        ],
        [
            "anticipation",
            "disbelief",
            "exasperation",
            "ambivalence",
            "bewilderment",
            "sadness",
        ],
        [
            "anticipation",
            "transcendence",
            "disbelief",
            "exasperation",
            "ambivalence",
            "bewilderment",
            "sadness",
        ],
    ],
    [
        ["anticipation", "sadness"],
        ["anticipation", "expectation", "sadness"],
        ["anticipation", "intrigue", "expectation", "sadness"],
        ["anticipation", "alertness", "intrigue", "expectation", "sadness"],
        [
            "anticipation",
            "interest",
            "alertness",
            "intrigue",
            "expectation",
            "sadness",
        ],
        [
            "anticipation",
            "curiosity",
            "interest",
            "alertness",
            "intrigue",
            "expectation",
            "sadness",
        ],
    ],
    [
        ["self-control", "thought"],
        ["self-control", "seriousness", "thought"],
        ["self-control", "wakefulness", "seriousness", "thought"],
        [
            "self-control",
            "ambivalence",
            "wakefulness",
            "seriousness",
            "thought",
        ],
        [
            "self-control",
            "imagination",
            "ambivalence",
            "wakefulness",
            "seriousness",
            "thought",
        ],
        [
            "self-control",
            "pensiveness",
            "imagination",
            "ambivalence",
            "wakefulness",
            "seriousness",
            "thought",
        ],
    ],
    [
        ["self-control", "thought"],
        ["self-control", "cognition", "thought"],
        ["self-control", "certainty", "cognition", "thought"],
        ["self-control", "planning", "certainty", "cognition", "thought"],
        [
            "self-control",
            "objectivity",
            "planning",
            "certainty",
            "cognition",
            "thought",
        ],
        [
            "self-control",
            "reason",
            "objectivity",
            "planning",
            "certainty",
            "cognition",
            "thought",
        ],
    ],
    [
        ["pity", "thought"],
        ["pity", "seriousness", "thought"],
        ["pity", "wakefulness", "seriousness", "thought"],
        ["pity", "ambivalence", "wakefulness", "seriousness", "thought"],
        [
            "pity",
            "imagination",
            "ambivalence",
            "wakefulness",
            "seriousness",
            "thought",
        ],
        [
            "pity",
            "pensiveness",
            "imagination",
            "ambivalence",
            "wakefulness",
            "seriousness",
            "thought",
        ],
    ],
    [
        ["pity", "thought"],
        ["pity", "remorse", "thought"],
        ["pity", "misery", "remorse", "thought"],
        ["pity", "uneasiness", "misery", "remorse", "thought"],
        ["pity", "despair", "uneasiness", "misery", "remorse", "thought"],
        [
            "pity",
            "bewilderment",
            "despair",
            "uneasiness",
            "misery",
            "remorse",
            "thought",
        ],
    ],
    [
        ["drowsiness", "tiredness"],
        ["drowsiness", "ambivalence", "tiredness"],
        ["drowsiness", "uncertainty", "ambivalence", "tiredness"],
        [
            "drowsiness",
            "contemplation",
            "uncertainty",
            "ambivalence",
            "tiredness",
        ],
        [
            "drowsiness",
            "doubt",
            "contemplation",
            "uncertainty",
            "ambivalence",
            "tiredness",
        ],
        [
            "drowsiness",
            "transcendence",
            "doubt",
            "contemplation",
            "uncertainty",
            "ambivalence",
            "tiredness",
        ],
    ],
    [
        ["drowsiness", "tiredness"],
        ["drowsiness", "laziness", "tiredness"],
        ["drowsiness", "lethargy", "laziness", "tiredness"],
        ["drowsiness", "trance", "lethargy", "laziness", "tiredness"],
        [
            "drowsiness",
            "sleepiness",
            "trance",
            "lethargy",
            "laziness",
            "tiredness",
        ],
        [
            "drowsiness",
            "fatigue",
            "sleepiness",
            "trance",
            "lethargy",
            "laziness",
            "tiredness",
        ],
    ],
    [
        ["anticipation", "tiredness"],
        ["anticipation", "ambivalence", "tiredness"],
        ["anticipation", "uncertainty", "ambivalence", "tiredness"],
        [
            "anticipation",
            "contemplation",
            "uncertainty",
            "ambivalence",
            "tiredness",
        ],
        [
            "anticipation",
            "doubt",
            "contemplation",
            "uncertainty",
            "ambivalence",
            "tiredness",
        ],
        [
            "anticipation",
            "transcendence",
            "doubt",
            "contemplation",
            "uncertainty",
            "ambivalence",
            "tiredness",
        ],
    ],
    [
        ["anticipation", "tiredness"],
        ["anticipation", "interest", "tiredness"],
        ["anticipation", "concern", "interest", "tiredness"],
        ["anticipation", "curiosity", "concern", "interest", "tiredness"],
        [
            "anticipation",
            "intrigue",
            "curiosity",
            "concern",
            "interest",
            "tiredness",
        ],
        [
            "anticipation",
            "alertness",
            "intrigue",
            "curiosity",
            "concern",
            "interest",
            "tiredness",
        ],
    ],
];

const stimSubset = [];

/* Out of all possible stim options, select a subset for the experiment.
Specifically, we select one from each of the 28 groups.
If we choose a one-step transition, we make sure not to pick the same 1-step transition from the next set */
for (var trial = 0; trial < stimOptions.length; trial++) {
    var index = Math.floor(Math.random() * (max - min + 1) + min);
    if (trial % 2 === 0) {
        if (index === 0) {
            stimOptions[trial + 1] = stimOptions[trial + 1].slice(1, 6);
        }
    }
    stimSubset.push(stimOptions[trial][index]);
}

/* Select a subset of the stimOptions */
 
stimSubset.sort(() => Math.random() - 0.5);

export default stimSubset;
